# Generated by Django 5.2.8 on 2025-11-12 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_band_active_band_biography_band_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("Records", "Records"),
                    ("Clothing", "Clothing"),
                    ("Posters", "Posters"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                default="Clothing",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="year_formed",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
    ]
